const invest = {
  address: {
    56: '0x59FD37b88780a7F5be75f0A5B9afeA7cf94eF0ff',
    97: '0x15dA682a2e9de3E0E2946F0f0D40675Da16DB4AE',
  },
  abi: [
    'event UpdateUser(address indexed user, uint256 value)',
    'event WithdrawInterest(address indexed user, uint256 hourly, uint256 referrals)',
    'event RegisterUser(address indexed user, address indexed referrer, uint256 value)',
    'function users(address) public view returns (address referrer,uint256 refEndTime,uint256 refAmounts,uint256 refPercent,uint256 totalAmount,uint256 latestWithdraw)',
    'function maxPercent() public view returns (uint256)',
    'function totalReward(uint256 value) public view returns (uint256)',
    'function rewardPercent(uint256 value) public view returns (uint256)',
    'function monthlyReward(uint256 value) public view returns (uint256)',
    'function hourlyReward(uint256 value) public view returns (uint256)',
    'function rewardPeriod(uint256 value) public view returns (uint256)',
    'function rewardInfo(uint256 value) public view returns (uint256 period,uint256 reward,uint256 endTime)',
    'function btcPrice() public view returns (uint256)',
    'function sttsToUSD(uint256 value) public view returns (uint256)',
    'function bnbToUSD(uint256 value) public view returns (uint256)',
    'function btcToUSD(uint256 value) public view returns (uint256)',
    'function sttToUSDPrice() public view returns (uint256)',
    'function USDToStts(uint256 value) public view returns (uint256)',
    'function referralInfo(address user, uint256 value)public view returns (uint256 totalAmount, uint256 refPercent)',
    'function investBnb(address referrer) public payable returns (bool)',
    'function investStts(address referrer, uint256 value) public returns (bool)',
    'function investBtcb(address referrer, uint256 value) public returns (bool)',
    'function updateBnb() public payable returns (bool)',
    'function updateStts(uint256 value) public returns (bool)',
    'function updateBtcb(uint256 value) public returns (bool)',
    'function withdrawInterest() public returns (bool)',
    'function calculateInterest(address sender) public view returns (uint256 hourly,uint256 referral,uint256 requestTime)',
    'function calculateHourly(address sender, uint256 time) public view returns (uint256 hourly)',
    'function userDepositNumber(address user) public view returns (uint256)',
    'function userDepositDetails(address user, uint256 index) public view returns (uint256 amount,uint256 period,uint256 reward,uint256 startTime,uint256 endTime)',
    'function userExpired(address user) public view returns (bool)',
  ],
}

export default invest
